config/routes.rb
Rails.application.routes.draw do
  resources :homes
  resources :inputforms

   root 'homes#index'

    

      resources :loans

end

app/controllers/inputforms_controller.rb
class InputformsController < ApplicationController
  before_action :set_inputform, only: [:show, :edit, :update, :destroy]

  # GET /inputforms
  # GET /inputforms.json
  def index
    @inputforms = Inputform.all
  end

  # GET /inputforms/1
  # GET /inputforms/1.json
  def show
    @tempinput = Inputform.find(params[:id])
    @temploan = Loan.where("loan_amnt > ?", 500).limit(1000)
    
    
    @listOfVectors = []
    @listOfIndex = []
    for loan in @temploan do
        newVector = [loan.loan_amnt.to_f,loan.installment.to_f, loan.annual_inc.to_f, loan.dti.to_f, loan.fico_range_low.to_f, loan.fico_range_high.to_f, loan.inq_last_6mths.to_f]
        @listOfVectors.push(newVector)
        @listOfIndex.push(loan.id)
    end 

    #We also need to change this to add both Euclidian distance and Cosine sim in display
    @inputVector = [ @tempinput.loan_amnt.to_f, @tempinput.installment.to_f, @tempinput.annual_inc.to_f, @tempinput.dti.to_f, @tempinput.fico_range_low.to_f, @tempinput.fico_range_high.to_f, @tempinput.number_inq_last_6months.to_f]
    knn = KNN.new(@listOfVectors, :distance_measure => :cosine_similarity)
    @nearestNeighborsCos = knn.nearest_neighbours( @inputVector, @tempinput.k.to_i)
    
    #@listOfVectorsCopy = Marshal.load( Marshal.dump(@listOfVectors) )
    knn2 = KNN.new(@listOfVectors, :distance_measure => :euclidean_distance)
    @nearestNeighborsEuc = knn2.nearest_neighbours( @inputVector, @tempinput.k.to_i)
    

    
    @paidStatusVec = []
    @numFullyPaid = 0.00
    @similarPeople = []
    @similarityScore = []
    @temp = 0
    
    for vec in @nearestNeighborsCos do
      temp = (Loan.find( @listOfIndex[vec.first] ))
      @similarityScore.push(vec.second)
      @similarPeople.push(temp)
      stringData = temp.loan_status.to_s
      if stringData.include? "Fully Paid"
        @paidStatusVec.push(1)
        @numFullyPaid = @numFullyPaid + 1.00
      else
        @paidStatusVec.push(0)
      end
    end 
    
    
    
    @paidStatusVec2 = []
    @numFullyPaid2 = 0.00
    @similarPeople2 = []
    @similarityScore2 = []
    @temp2 = 0

    
    for vec in @nearestNeighborsEuc do
      temp = (Loan.find( @listOfIndex[vec.first] ))
      @similarityScore2.push(vec.second)
      @similarPeople2.push(temp)
      stringData = temp.loan_status.to_s
      if stringData.include? "Fully Paid"
        @paidStatusVec2.push(1)
        @numFullyPaid2 = @numFullyPaid2 + 1.00
      else
        @paidStatusVec2.push(0)
      end
    end 
    
    
  end

  # GET /inputforms/new
  def new
    @inputform = Inputform.new
  end

  # GET /inputforms/1/edit
  def edit
  end

  # POST /inputforms
  # POST /inputforms.json
  def create
    @inputform = Inputform.new(inputform_params)

    respond_to do |format|
      if @inputform.save
        format.html { redirect_to @inputform, notice: 'Inputform was successfully created.' }
        format.json { render :show, status: :created, location: @inputform }
      else
        format.html { render :new }
        format.json { render json: @inputform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputforms/1
  # PATCH/PUT /inputforms/1.json
  def update
    respond_to do |format|
      if @inputform.update(inputform_params)
        format.html { redirect_to @inputform, notice: 'Inputform was successfully updated.' }
        format.json { render :show, status: :ok, location: @inputform }
      else
        format.html { render :edit }
        format.json { render json: @inputform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputforms/1
  # DELETE /inputforms/1.json
  def destroy
    @inputform.destroy
    respond_to do |format|
      format.html { redirect_to inputforms_url, notice: 'Inputform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inputform
      @inputform = Inputform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inputform_params
      params.require(:inputform).permit(:loan_amnt, :installment, :grade, :emp_length, :annual_inc, :dti, :fico_range_low, :fico_range_high, :number_inq_last_6months, :k)
    end
end

app/helpers/inputforms_helper.rb
module InputformsHelper
end

app/views/inputforms/_form.html.erb
<%= form_for(@inputform) do |f| %>
  <% if @inputform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inputform.errors.count, "error") %> prohibited this inputform from being saved:</h2>

      <ul>
      <% @inputform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<div class="panel panel-info">
  <div class="panel-heading">
    Your Information: <strong> Input Vector </strong>
  </div>
  <div class="panel-body">
  <table class="table table-bordered table-hover table-striped">
    <tr>
      <th>Loan Amount</th>
      <th>Installment</th>
      <th>Grade</th>
      <th>Employment Length</th>
      <th>Annual Income</th>
      <th>Debt to Income Ratio</th>
      <th>FCL</th>
      <th>FCH</th>
      <th>Number Inquires (6 Months)</th>
      <th>K neighbors</th>
    </tr>
    
    <tr>
      <th><div class="field form-group">
    <%= f.text_field :loan_amnt,class: 'form-control' %>
          </div>
      </th>
      <th><div class="field form-group">
    <%= f.text_field :installment,class: 'form-control' %>
  </div></th>
      <th><div class="field form-group">
    <%= f.text_field :grade, class: 'form-control' %>
  </div></th>
      <th><div class="field form-group">
    <%= f.text_field :emp_length,class: 'form-control' %>
  </div></th>
      <th><div class="field form-group">
    <%= f.text_field :annual_inc,class: 'form-control' %>
  </div></th>
      <th><div class="field form-group">
    <%= f.text_field :dti,class: 'form-control' %>
  </div></th>
      <th><div class="field form-group">
    <%= f.text_field :fico_range_low,class: 'form-control' %>
  </div></th>
      <th><div class="field form-group">
    <%= f.text_field :fico_range_high,class: 'form-control' %>
  </div></th>
      <th><div class="field form-group">
    <%= f.text_field :number_inq_last_6months,class: 'form-control' %>
  </div></th>
      <th><div class="field form-group">
    <%= f.text_field :k,class: 'form-control' %>
  </div></th>
    </tr>
    
  </table>
  
  </div>
</div>
  <div class="actions form-group">
    <div class="col-sm-offset-0 col-sm-10">
      <%= f.submit class: 'btn btn-lg btn-primary'%>
    </div>
  </div>
  </div>
<% end %>

      
    
    
    
        <img src="http://s32.postimg.org/j9gdp6xsl/lendingclub_investor_screenshot.png">
   

app/views/inputforms/edit.html.erb
<h1>Editing Inputform</h1>

<%= render 'form' %>

<%= link_to 'Show', @inputform %> |
<%= link_to 'Back', inputforms_path %>

app/views/inputforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inputforms</h1>

<table>
  <thead>
    <tr>
      <th>Loan amnt</th>
      <th>Installment</th>
      <th>Grade</th>
      <th>Emp length</th>
      <th>Annual inc</th>
      <th>Dti</th>
      <th>Fico range low</th>
      <th>Fico range high</th>
      <th>Number inq last 6months</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inputforms.each do |inputform| %>
      <tr>
        <td><%= inputform.loan_amnt %></td>
        <td><%= inputform.installment %></td>
        <td><%= inputform.grade %></td>
        <td><%= inputform.emp_length %></td>
        <td><%= inputform.annual_inc %></td>
        <td><%= inputform.dti %></td>
        <td><%= inputform.fico_range_low %></td>
        <td><%= inputform.fico_range_high %></td>
        <td><%= inputform.number_inq_last_6months %></td>
        <td><%= link_to 'Show', inputform %></td>
        <td><%= link_to 'Edit', edit_inputform_path(inputform) %></td>
        <td><%= link_to 'Destroy', inputform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inputform', new_inputform_path %>

app/views/inputforms/new.html.erb
<h1> Enter Your Loan</h1>

<%= render 'form' %>

app/views/inputforms/show.html.erb
<blockquote>
<div class="panel panel-info">
  <div class="panel-heading">
    Your Information: <strong> Input Vector </strong>
  </div>
  <div class="panel-body">
  <table class="table table-bordered table-hover table-striped">
    <tr>
      <th>Loan Amount</th>
      <th>Installment</th>
      <th>Grade</th>
      <th>Employment Length</th>
      <th>Annual Income</th>
      <th>Debt to Income Ratio</th>
      <th>FCL</th>
      <th>FCH</th>
      <th>Number Inquires (6 Months)</th>
      <th>K neighbors</th>
    </tr>
    
    <tr>
      <th><%= @inputform.loan_amnt %></th>
      <th><%= @inputform.installment %></th>
      <th><%= @inputform.grade %></th>
      <th><%= @inputform.emp_length %></th>
      <th><%= @inputform.annual_inc %></th>
      <th><%= @inputform.dti %>%</th>
      <th><%= @inputform.fico_range_low %></th>
      <th><%= @inputform.fico_range_high %></th>
      <th><%= @inputform.number_inq_last_6months %></th>
      <th><%= @inputform.k %></th>
    </tr>
    
  </table>
  
  </div>
</div>



<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Result</h3>
  </div>
  <div class="panel-body">
    <div class="jumbotron">
      <h1><%=  100.00* (@numFullyPaid / @tempinput.k.to_f) %>% </h1>
        
      <p>Using <%= @inputform.k %> neighbors and Cosine similarity</p>
    </div>
  </div>
</div>

<div class="panel panel-info" >
  <div class="panel-heading" data-toggle="collapse" data-target="#demo">
    <h3 class="panel-title">People who are similar</h3>
  </div>
  <div class="panel-body" id="demo" class="collapse">
    <table class="table table-bordered table-hover table-striped">
    <tr>
      <th>Cosine % Similar</th>
      <th>Loan Amount</th>
      <th>Installment</th>
      <th>Grade</th>
      <th>Employment Length</th>
      <th>Annual Income</th>
      <th>Debt to Income Ratio</th>
      <th>FCL</th>
      <th>FCH</th>
    </tr>
    <% @similarityScore = @similarityScore.reverse  %>
    <% @similarPeople.reverse.first(10).each do |temp| %>
      <tr>
        <th> <%= (100.00 *  @similarityScore[@temp]).round(2) %>%  </th>
        <th><%= temp.loan_amnt %></th>
        <th><%= temp.installment %></th>
        <th><%= temp.grade %></th>
        <th><%= temp.emp_length %></th>
        <th><%= temp.annual_inc %></th>
        <th><%= temp.dti %>%</th>
        <th><%= temp.fico_range_low %></th>
        <th><%= temp.fico_range_high %></th>
      </tr>
      <% @temp = @temp + 1 %>
    <% end %>

    
  </table>
    
    
    
    
    

  </div>
</div>








<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Result</h3>
  </div>
  <div class="panel-body">
    <div class="jumbotron">
      <h1><%=  100.00* (@numFullyPaid2 / @tempinput.k.to_f) %>% </h1>
      <p>Using <%= @inputform.k %> neighbors and Euclidian Distance</p>
    </div>
  </div>
</div>




<div class="panel panel-info" >
  <div class="panel-heading" data-toggle="collapse" data-target="#demo">
    <h3 class="panel-title">People who are similar</h3>
  </div>
  <div class="panel-body" id="demo" class="collapse">
    <table class="table table-bordered table-hover table-striped">
    <tr>
      <th>Euclidian Distance</th>
      <th>Loan Amount</th>
      <th>Installment</th>
      <th>Grade</th>
      <th>Employment Length</th>
      <th>Annual Income</th>
      <th>Debt to Income Ratio</th>
      <th>FCL</th>
      <th>FCH</th>
    </tr>
    
    <% @similarPeople2.reverse.first(10).each do |temp| %>
      <tr>
        <th> <%=   @similarityScore2[@temp2].round(2) %>  </th>
        <th><%= temp.loan_amnt %></th>
        <th><%= temp.installment %></th>
        <th><%= temp.grade %></th>
        <th><%= temp.emp_length %></th>
        <th><%= temp.annual_inc %></th>
        <th><%= temp.dti %>%</th>
        <th><%= temp.fico_range_low %></th>
        <th><%= temp.fico_range_high %></th>
      </tr>
      <% @temp2 = @temp2 + 1 %>
    <% end %>

    
  </table>
    

  </div>
</div>


<br>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">We compared your input to <%= @listOfVectors.size %> other loans below: </h3>
  </div>
  <div class="panel-body">
    <div style="height:200px;width:100%;overflow:auto;color:black;scrollbar-base-color:gold;font-family:sans-serif;padding:10px;border:2px solid green;">
    <%= @listOfVectors.each do |temp| %>
       <tr><th><% temp %></th></tr>
    <% end %>
    </div>
    
  </div>
</div>





</blockquote>


<%= link_to 'Edit', edit_inputform_path(@inputform) %> |
<%= link_to 'Back', inputforms_path %>